# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres!
  host: 0.0.0.0
  port: 5432
  pool: 5

development:
  <<: *default
  database: storeStripe_development


test:
  <<: *default
  database: storeStripe_test

production:
  <<: *default
  database: storeStripe_production